### ISSUE TITLE
deploy fixed cloud CAU

### ISSUE THREAD

**Issue by cjdcordeiro** [mF2C/cau-client#1]
needs mF2C/mF2C#96

**Comment by syc17** [comment]
I think there should be two issues here:
1) fix CA (STFC)
2) deploy cloud CAU (UPC, STFC)  - UPC wrote the CAU in IT-1

**Comment by syc17** [comment]
CA is fixed as of last month.  UPC (Alejandro) is in the process of deploying a Cloud CAU on the same machine running the CA service.

**Comment by syc17** [comment]
Hi Alejandro, your fixed CAU in the cloud needs to be trusted by the CAU client.  It needs to have a certificate issued by the IT2trustedCA.

**Comment by ALEJANDROJ19** [comment]
For the record, the CA was completely fixed (HTTPs Connection) on [January 28th](https://github.com/mF2C/certauth/commit/d1f6afff0329b6e3e7813927e6536440de5cad47) and we started our changes this week, as we plan to release today if everything works. Pau and @mrsarang have done the testing with the new CA and work well and today I'll check if the whole workflow works. If i have any trouble deploying the CAU in the cloud I'll let you know.

**Comment by ALEJANDROJ19** [comment]
CAU deployed in cloud (same machine as CA). We still have an issue (mF2C/mF2C#116) in the integration, but it's deployed successfully. Also, we created a new repository with the code, open to anyone that wants to contribute https://github.com/mF2C/CAU

**Comment by ALEJANDROJ19** [comment]
As a reminder, the CAU in the cloud is only for implementation and integration tests. The concept of having an element in the cloud that controls other CAUs and does other functionalities is out of the scope from our side.
